edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

use_small_heuristics = "Off"

newline_style = "Unix"
reorder_imports = true

match_block_trailing_comma = true
trailing_comma = "Never"