CREATE TABLE IF NOT EXISTS mfa_methods (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    method_type VARCHAR(50) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, method_type)
);

CREATE INDEX mfa_methods_user_id_idx ON mfa_methods(user_id);

ALTER TABLE mfa_methods ADD COLUMN IF NOT EXISTS secret VARCHAR(255);
ALTER TABLE mfa_methods ADD COLUMN IF NOT EXISTS verified BOOLEAN DEFAULT FALSE;
ALTER TABLE mfa_methods ADD COLUMN IF NOT EXISTS last_used_at TIMESTAMP WITH TIME ZONE;