ALTER TABLE users
    ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS password_history TEXT[] DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS password_expires_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS require_password_change BOOLEAN NOT NULL DEFAULT FALSE;